version: '3.1'

services:

  redis:
    image: redis
    restart: always
    ports:
     - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  app:
    build:
      context: .
    ports:
      - 3000:3000
    restart: always
#    volumes:
#      - ./conf/app.compose.ini:/home/conf/app_dev.ini
    depends_on:
      - redis
