version: '3.1'

#networks:
#  proxy-net:
#    external:
#      name: proxypool_default

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  app:
    build:
      context: ./proxypool
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    #    volumes:
    #      - ./conf/app.compose.ini:/home/conf/app_dev.ini
    depends_on:
      - redis
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./proxypool/conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./proxypool/conf/node_down.yml:/etc/prometheus/node_down.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    volumes:
      - ./proxypool/conf/grafana/provisioning/dashboards:/usr/share/grafana/conf/provisioning/dashboards
    ports:
      - "3001:3000"
  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always


#  bdd:
#    build:
#      context: .
#    ports:
#      - 8080:8080
#    restart: always
#    depends_on:
#      - app

#    networks:
#      - proxy-net
#    volumes:
#      - ./conf/app.compose.ini:/home/conf/app_dev.ini